In [1]:
#!/usr/bin/python3
import requests
import json

### Part 1 Getting the Data from the API ###

data = requests.get("https://ebola-outbreak.p.mashape.com/cases",
  headers={
    "X-Mashape-Key": "5wOSqCitXnmshZqducSXXSpnMgA0p1SQfb8jsnticr7ef6tPYu"
  }
)

In [2]:
data = data.text

In [3]:
data = json.loads(data)

In [4]:
data

[{'cases': 49,
  'date': '2014-03-23T00:00:00.000Z',
  'deaths': 29,
  'status': 'confirmed'},
 {'cases': 86,
  'date': '2014-03-24T00:00:00.000Z',
  'deaths': 59,
  'status': 'confirmed'},
 {'cases': 111,
  'date': '2014-03-27T00:00:00.000Z',
  'deaths': 72,
  'status': 'confirmed'},
 {'cases': 114,
  'date': '2014-03-30T00:00:00.000Z',
  'deaths': 72,
  'status': 'confirmed'},
 {'cases': 129,
  'date': '2014-04-02T00:00:00.000Z',
  'deaths': 85,
  'status': 'confirmed'},
 {'cases': 161,
  'date': '2014-04-05T00:00:00.000Z',
  'deaths': 93,
  'status': 'confirmed'},
 {'cases': 172,
  'date': '2014-04-07T00:00:00.000Z',
  'deaths': 105,
  'status': 'confirmed'},
 {'cases': 183,
  'date': '2014-04-10T00:00:00.000Z',
  'deaths': 111,
  'status': 'confirmed'},
 {'cases': 236,
  'date': '2014-04-17T00:00:00.000Z',
  'deaths': 135,
  'status': 'confirmed'},
 {'cases': 270,
  'date': '2014-05-06T00:00:00.000Z',
  'deaths': 168,
  'status': 'confirmed'},
 {'cases': 275,
  'date': '2014-05-09T00:00:00.000Z',
  'deaths': 171,
  'status': 'confirmed'},
 {'cases': 287,
  'date': '2014-05-15T00:00:00.000Z',
  'deaths': 184,
  'status': 'confirmed'},
 {'cases': 324,
  'date': '2014-05-28T00:00:00.000Z',
  'deaths': 204,
  'status': 'confirmed'},
 {'cases': 368,
  'date': '2014-05-30T00:00:00.000Z',
  'deaths': 212,
  'status': 'confirmed'},
 {'cases': 434,
  'date': '2014-06-04T00:00:00.000Z',
  'deaths': 227,
  'status': 'confirmed'},
 {'cases': 442,
  'date': '2014-06-06T00:00:00.000Z',
  'deaths': 234,
  'status': 'confirmed'},
 {'cases': 467,
  'date': '2014-06-10T00:00:00.000Z',
  'deaths': 246,
  'status': 'confirmed'},
 {'cases': 528,
  'date': '2014-06-18T00:00:00.000Z',
  'deaths': 337,
  'status': 'confirmed'},
 {'cases': 599,
  'date': '2014-06-24T00:00:00.000Z',
  'deaths': 338,
  'status': 'confirmed'},
 {'cases': 759,
  'date': '2014-07-01T00:00:00.000Z',
  'deaths': 467,
  'status': 'confirmed'},
 {'cases': 779,
  'date': '2014-07-03T00:00:00.000Z',
  'deaths': 481,
  'status': 'confirmed'},
 {'cases': 844,
  'date': '2014-07-08T00:00:00.000Z',
  'deaths': 518,
  'status': 'confirmed'},
 {'cases': 888,
  'date': '2014-07-10T00:00:00.000Z',
  'deaths': 539,
  'status': 'confirmed'},
 {'cases': 982,
  'date': '2014-07-17T00:00:00.000Z',
  'deaths': 613,
  'status': 'confirmed'},
 {'cases': 1048,
  'date': '2014-07-19T00:00:00.000Z',
  'deaths': 632,
  'status': 'confirmed'},
 {'cases': 1093,
  'date': '2014-07-24T00:00:00.000Z',
  'deaths': 660,
  'status': 'confirmed'},
 {'cases': 1201,
  'date': '2014-07-27T00:00:00.000Z',
  'deaths': 672,
  'status': 'confirmed'},
 {'cases': 1322,
  'date': '2014-07-31T00:00:00.000Z',
  'deaths': 729,
  'status': 'confirmed'},
 {'cases': 1603,
  'date': '2014-08-04T00:00:00.000Z',
  'deaths': 887,
  'status': 'confirmed'},
 {'cases': 1711,
  'date': '2014-08-06T00:00:00.000Z',
  'deaths': 932,
  'status': 'confirmed'},
 {'cases': 1779,
  'date': '2014-08-08T00:00:00.000Z',
  'deaths': 961,
  'status': 'confirmed'},
 {'cases': 1868,
  'date': '2014-08-11T00:00:00.000Z',
  'deaths': 1013,
  'status': 'confirmed'},
 {'cases': 1975,
  'date': '2014-08-12T00:00:00.000Z',
  'deaths': 1069,
  'status': 'confirmed'},
 {'cases': 2127,
  'date': '2014-08-14T00:00:00.000Z',
  'deaths': 1145,
  'status': 'confirmed'},
 {'cases': 2473,
  'date': '2014-08-19T00:00:00.000Z',
  'deaths': 1350,
  'status': 'confirmed'},
 {'cases': 2615,
  'date': '2014-08-21T00:00:00.000Z',
  'deaths': 1427,
  'status': 'confirmed'},
 {'cases': 2656,
  'date': '2014-08-27T00:00:00.000Z',
  'deaths': 1451,
  'status': 'confirmed'},
 {'cases': 3069,
  'date': '2014-08-28T00:00:00.000Z',
  'deaths': 1552,
  'status': 'confirmed'},
 {'cases': 3070,
  'date': '2014-08-30T00:00:00.000Z',
  'deaths': 1552,
  'status': 'confirmed'},
 {'cases': 3967,
  'date': '2014-09-05T00:00:00.000Z',
  'deaths': 2105,
  'status': 'confirmed'},
 {'cases': 4291,
  'date': '2014-09-09T00:00:00.000Z',
  'deaths': 2296,
  'status': 'confirmed'},
 {'cases': 4985,
  'date': '2014-09-16T00:00:00.000Z',
  'deaths': 2461,
  'status': 'confirmed'},
 {'cases': 5347,
  'date': '2014-09-18T00:00:00.000Z',
  'deaths': 2630,
  'status': 'confirmed'},
 {'cases': 5864,
  'date': '2014-09-20T00:00:00.000Z',
  'deaths': 2811,
  'status': 'confirmed'},
 {'cases': 6263,
  'date': '2014-09-24T00:00:00.000Z',
  'deaths': 2917,
  'status': 'confirmed'},
 {'cases': 7178,
  'date': '2014-10-01T00:00:00.000Z',
  'deaths': 3338,
  'status': 'confirmed'},
 {'cases': 7492,
  'date': '2014-10-03T00:00:00.000Z',
  'deaths': 3439,
  'status': 'confirmed'},
 {'cases': 8034,
  'date': '2014-10-08T00:00:00.000Z',
  'deaths': 3865,
  'status': 'confirmed'},
 {'cases': 8399,
  'date': '2014-10-10T00:00:00.000Z',
  'deaths': 4033,
  'status': 'confirmed'},
 {'cases': 8997,
  'date': '2014-10-15T00:00:00.000Z',
  'deaths': 4493,
  'status': 'confirmed'},
 {'cases': 9216,
  'date': '2014-10-17T00:00:00.000Z',
  'deaths': 4555,
  'status': 'confirmed'},
 {'cases': 9936,
  'date': '2014-10-22T00:00:00.000Z',
  'deaths': 4877,
  'status': 'confirmed'},
 {'cases': 10141,
  'date': '2014-10-25T00:00:00.000Z',
  'deaths': 4922,
  'status': 'confirmed'},
 {'cases': 13703,
  'date': '2014-10-29T00:00:00.000Z',
  'deaths': 4920,
  'status': 'confirmed'},
 {'cases': 13567,
  'date': '2014-10-31T00:00:00.000Z',
  'deaths': 4951,
  'status': 'confirmed'},
 {'cases': 13042,
  'date': '2014-11-05T00:00:00.000Z',
  'deaths': 4818,
  'status': 'confirmed'},
 {'cases': 13268,
  'date': '2014-11-07T00:00:00.000Z',
  'deaths': 4960,
  'status': 'confirmed'},
 {'cases': 14098,
  'date': '2014-11-12T00:00:00.000Z',
  'deaths': 5160,
  'status': 'confirmed'},
 {'cases': 14413,
  'date': '2014-11-14T00:00:00.000Z',
  'deaths': 5177,
  'status': 'confirmed'},
 {'cases': 15145,
  'date': '2014-11-19T00:00:00.000Z',
  'deaths': 5420,
  'status': 'confirmed'},
 {'cases': 15351,
  'date': '2014-11-21T00:00:00.000Z',
  'deaths': 5459,
  'status': 'confirmed'},
 {'cases': 15935,
  'date': '2014-11-26T00:00:00.000Z',
  'deaths': 5689,
  'status': 'confirmed'},
 {'cases': 17145,
  'date': '2014-12-03T00:00:00.000Z',
  'deaths': 6070,
  'status': 'confirmed'},
 {'cases': 17942,
  'date': '2014-12-10T00:00:00.000Z',
  'deaths': 6388,
  'status': 'confirmed'},
 {'cases': 18603,
  'date': '2014-12-17T00:00:00.000Z',
  'deaths': 6915,
  'status': 'confirmed'},
 {'cases': 19497,
  'date': '2014-12-24T00:00:00.000Z',
  'deaths': 7588,
  'status': 'confirmed'},
 {'cases': 20206,
  'date': '2014-12-31T00:00:00.000Z',
  'deaths': 7905,
  'status': 'confirmed'},
 {'cases': 20747,
  'date': '2015-01-07T00:00:00.000Z',
  'deaths': 8235,
  'status': 'confirmed'},
 {'cases': 21296,
  'date': '2015-01-14T00:00:00.000Z',
  'deaths': 8429,
  'status': 'confirmed'},
 {'cases': 21724,
  'date': '2015-01-21T00:00:00.000Z',
  'deaths': 8641,
  'status': 'confirmed'},
 {'cases': 22092,
  'date': '2015-01-28T00:00:00.000Z',
  'deaths': 8810,
  'status': 'confirmed'},
 {'cases': 22495,
  'date': '2015-02-04T00:00:00.000Z',
  'deaths': 8981,
  'status': 'confirmed'},
 {'cases': 22894,
  'date': '2015-02-11T00:00:00.000Z',
  'deaths': 9177,
  'status': 'confirmed'},
 {'cases': 23253,
  'date': '2015-02-18T00:00:00.000Z',
  'deaths': 9380,
  'status': 'confirmed'},
 {'cases': 23729,
  'date': '2015-02-25T00:00:00.000Z',
  'deaths': 9604,
  'status': 'confirmed'},
 {'cases': 23969,
  'date': '2015-03-04T00:00:00.000Z',
  'deaths': 9807,
  'status': 'confirmed'},
 {'cases': 24282,
  'date': '2015-03-11T00:00:00.000Z',
  'deaths': 9976,
  'status': 'confirmed'},
 {'cases': 24701,
  'date': '2015-03-18T00:00:00.000Z',
  'deaths': 10194,
  'status': 'confirmed'},
 {'cases': 24907,
  'date': '2015-03-25T00:00:00.000Z',
  'deaths': 10326,
  'status': 'confirmed'}]

In [5]:
data[78]['cases']

24907

In [6]:
import MySQLdb as mdb
import sys

con = mdb.connect(host = 'localhost', 
                  user = 'root', 
                  passwd = 'dwdstudent2015', 
                  charset='utf8', use_unicode=True);


# Create the Ebola database
db_name = 'Ebola'
create_db_query = "CREATE DATABASE IF NOT EXISTS {db} DEFAULT CHARACTER SET 'utf8'".format(db=db_name)

# Create a database
cursor = con.cursor()
cursor.execute(create_db_query)
cursor.close()

/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:16: Warning: (1007, "Can't create database 'Ebola'; database exists")

In [7]:
cursor = con.cursor()
db_name = 'Ebola'
table_name = 'Cases'
# Create a table

create_table_query = '''CREATE TABLE IF NOT EXISTS {db}.{table} 
                                (cases int,
                                date datetime,
                                deaths int,
                                status varchar(250), 
                                PRIMARY KEY(date)
                                )'''.format(db=db_name, table=table_name)
cursor.execute(create_table_query)
cursor.close()

/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:13: Warning: (1050, "Table 'Cases' already exists")

In [9]:
from datetime import date, datetime, timedelta

query_template = '''INSERT INTO 
    Ebola.Cases(cases, date, deaths, status) 
    VALUES (%s, %s, %s, %s)'''

cursor = con.cursor()

for entry in data:
    cases = entry['cases']
    
    date_split = entry['date'][0:10]
    
    date = datetime.strptime(date_split, 
                         '%Y-%m-%d')

    deaths = entry['deaths']
    status = entry['status']
    
    
    print("Inserting case", cases)
    query_parameters = (cases, date, deaths, status)
    cursor.execute(query_template, query_parameters)

con.commit()
cursor.close()

Inserting case 49
Inserting case 86
Inserting case 111
Inserting case 114
Inserting case 129
Inserting case 161
Inserting case 172
Inserting case 183
Inserting case 236
Inserting case 270
Inserting case 275
Inserting case 287
Inserting case 324
Inserting case 368
Inserting case 434
Inserting case 442
Inserting case 467
Inserting case 528
Inserting case 599
Inserting case 759
Inserting case 779
Inserting case 844
Inserting case 888
Inserting case 982
Inserting case 1048
Inserting case 1093
Inserting case 1201
Inserting case 1322
Inserting case 1603
Inserting case 1711
Inserting case 1779
Inserting case 1868
Inserting case 1975
Inserting case 2127
Inserting case 2473
Inserting case 2615
Inserting case 2656
Inserting case 3069
Inserting case 3070
Inserting case 3967
Inserting case 4291
Inserting case 4985
Inserting case 5347
Inserting case 5864
Inserting case 6263
Inserting case 7178
Inserting case 7492
Inserting case 8034
Inserting case 8399
Inserting case 8997
Inserting case 9216
Inserting case 9936
Inserting case 10141
Inserting case 13703
Inserting case 13567
Inserting case 13042
Inserting case 13268
Inserting case 14098
Inserting case 14413
Inserting case 15145
Inserting case 15351
Inserting case 15935
Inserting case 17145
Inserting case 17942
Inserting case 18603
Inserting case 19497
Inserting case 20206
Inserting case 20747
Inserting case 21296
Inserting case 21724
Inserting case 22092
Inserting case 22495
Inserting case 22894
Inserting case 23253
Inserting case 23729
Inserting case 23969
Inserting case 24282
Inserting case 24701
Inserting case 24907

In [10]:
cur = con.cursor(mdb.cursors.DictCursor)
cur.execute("SELECT * FROM Ebola.Cases")
rows = cur.fetchall()

In [11]:
for row in rows:
    print("Case ID:", row["cases"])
    print("Date:", row["date"])
    print("Number of Deaths:", row["deaths"])
    print("Status:", row["status"])
    print("=============================================")
    
cur.close()

Case ID: 49
Date: 2014-03-02 00:00:00
Number of Deaths: 29
Status: confirmed
=============================================
Case ID: 49
Date: 2014-03-23 00:00:00
Number of Deaths: 29
Status: confirmed
=============================================
Case ID: 86
Date: 2014-03-24 00:00:00
Number of Deaths: 59
Status: confirmed
=============================================
Case ID: 111
Date: 2014-03-27 00:00:00
Number of Deaths: 72
Status: confirmed
=============================================
Case ID: 114
Date: 2014-03-30 00:00:00
Number of Deaths: 72
Status: confirmed
=============================================
Case ID: 129
Date: 2014-04-02 00:00:00
Number of Deaths: 85
Status: confirmed
=============================================
Case ID: 161
Date: 2014-04-05 00:00:00
Number of Deaths: 93
Status: confirmed
=============================================
Case ID: 172
Date: 2014-04-07 00:00:00
Number of Deaths: 105
Status: confirmed
=============================================
Case ID: 183
Date: 2014-04-10 00:00:00
Number of Deaths: 111
Status: confirmed
=============================================
Case ID: 236
Date: 2014-04-17 00:00:00
Number of Deaths: 135
Status: confirmed
=============================================
Case ID: 270
Date: 2014-05-06 00:00:00
Number of Deaths: 168
Status: confirmed
=============================================
Case ID: 275
Date: 2014-05-09 00:00:00
Number of Deaths: 171
Status: confirmed
=============================================
Case ID: 287
Date: 2014-05-15 00:00:00
Number of Deaths: 184
Status: confirmed
=============================================
Case ID: 324
Date: 2014-05-28 00:00:00
Number of Deaths: 204
Status: confirmed
=============================================
Case ID: 368
Date: 2014-05-30 00:00:00
Number of Deaths: 212
Status: confirmed
=============================================
Case ID: 434
Date: 2014-06-04 00:00:00
Number of Deaths: 227
Status: confirmed
=============================================
Case ID: 442
Date: 2014-06-06 00:00:00
Number of Deaths: 234
Status: confirmed
=============================================
Case ID: 467
Date: 2014-06-10 00:00:00
Number of Deaths: 246
Status: confirmed
=============================================
Case ID: 528
Date: 2014-06-18 00:00:00
Number of Deaths: 337
Status: confirmed
=============================================
Case ID: 599
Date: 2014-06-24 00:00:00
Number of Deaths: 338
Status: confirmed
=============================================
Case ID: 759
Date: 2014-07-01 00:00:00
Number of Deaths: 467
Status: confirmed
=============================================
Case ID: 779
Date: 2014-07-03 00:00:00
Number of Deaths: 481
Status: confirmed
=============================================
Case ID: 844
Date: 2014-07-08 00:00:00
Number of Deaths: 518
Status: confirmed
=============================================
Case ID: 888
Date: 2014-07-10 00:00:00
Number of Deaths: 539
Status: confirmed
=============================================
Case ID: 982
Date: 2014-07-17 00:00:00
Number of Deaths: 613
Status: confirmed
=============================================
Case ID: 1048
Date: 2014-07-19 00:00:00
Number of Deaths: 632
Status: confirmed
=============================================
Case ID: 1093
Date: 2014-07-24 00:00:00
Number of Deaths: 660
Status: confirmed
=============================================
Case ID: 1201
Date: 2014-07-27 00:00:00
Number of Deaths: 672
Status: confirmed
=============================================
Case ID: 1322
Date: 2014-07-31 00:00:00
Number of Deaths: 729
Status: confirmed
=============================================
Case ID: 1603
Date: 2014-08-04 00:00:00
Number of Deaths: 887
Status: confirmed
=============================================
Case ID: 1711
Date: 2014-08-06 00:00:00
Number of Deaths: 932
Status: confirmed
=============================================
Case ID: 1779
Date: 2014-08-08 00:00:00
Number of Deaths: 961
Status: confirmed
=============================================
Case ID: 1868
Date: 2014-08-11 00:00:00
Number of Deaths: 1013
Status: confirmed
=============================================
Case ID: 1975
Date: 2014-08-12 00:00:00
Number of Deaths: 1069
Status: confirmed
=============================================
Case ID: 2127
Date: 2014-08-14 00:00:00
Number of Deaths: 1145
Status: confirmed
=============================================
Case ID: 2473
Date: 2014-08-19 00:00:00
Number of Deaths: 1350
Status: confirmed
=============================================
Case ID: 2615
Date: 2014-08-21 00:00:00
Number of Deaths: 1427
Status: confirmed
=============================================
Case ID: 2656
Date: 2014-08-27 00:00:00
Number of Deaths: 1451
Status: confirmed
=============================================
Case ID: 3069
Date: 2014-08-28 00:00:00
Number of Deaths: 1552
Status: confirmed
=============================================
Case ID: 3070
Date: 2014-08-30 00:00:00
Number of Deaths: 1552
Status: confirmed
=============================================
Case ID: 3967
Date: 2014-09-05 00:00:00
Number of Deaths: 2105
Status: confirmed
=============================================
Case ID: 4291
Date: 2014-09-09 00:00:00
Number of Deaths: 2296
Status: confirmed
=============================================
Case ID: 4985
Date: 2014-09-16 00:00:00
Number of Deaths: 2461
Status: confirmed
=============================================
Case ID: 5347
Date: 2014-09-18 00:00:00
Number of Deaths: 2630
Status: confirmed
=============================================
Case ID: 5864
Date: 2014-09-20 00:00:00
Number of Deaths: 2811
Status: confirmed
=============================================
Case ID: 6263
Date: 2014-09-24 00:00:00
Number of Deaths: 2917
Status: confirmed
=============================================
Case ID: 7178
Date: 2014-10-01 00:00:00
Number of Deaths: 3338
Status: confirmed
=============================================
Case ID: 7492
Date: 2014-10-03 00:00:00
Number of Deaths: 3439
Status: confirmed
=============================================
Case ID: 8034
Date: 2014-10-08 00:00:00
Number of Deaths: 3865
Status: confirmed
=============================================
Case ID: 8399
Date: 2014-10-10 00:00:00
Number of Deaths: 4033
Status: confirmed
=============================================
Case ID: 8997
Date: 2014-10-15 00:00:00
Number of Deaths: 4493
Status: confirmed
=============================================
Case ID: 9216
Date: 2014-10-17 00:00:00
Number of Deaths: 4555
Status: confirmed
=============================================
Case ID: 9936
Date: 2014-10-22 00:00:00
Number of Deaths: 4877
Status: confirmed
=============================================
Case ID: 10141
Date: 2014-10-25 00:00:00
Number of Deaths: 4922
Status: confirmed
=============================================
Case ID: 13703
Date: 2014-10-29 00:00:00
Number of Deaths: 4920
Status: confirmed
=============================================
Case ID: 13567
Date: 2014-10-31 00:00:00
Number of Deaths: 4951
Status: confirmed
=============================================
Case ID: 13042
Date: 2014-11-05 00:00:00
Number of Deaths: 4818
Status: confirmed
=============================================
Case ID: 13268
Date: 2014-11-07 00:00:00
Number of Deaths: 4960
Status: confirmed
=============================================
Case ID: 14098
Date: 2014-11-12 00:00:00
Number of Deaths: 5160
Status: confirmed
=============================================
Case ID: 14413
Date: 2014-11-14 00:00:00
Number of Deaths: 5177
Status: confirmed
=============================================
Case ID: 15145
Date: 2014-11-19 00:00:00
Number of Deaths: 5420
Status: confirmed
=============================================
Case ID: 15351
Date: 2014-11-21 00:00:00
Number of Deaths: 5459
Status: confirmed
=============================================
Case ID: 15935
Date: 2014-11-26 00:00:00
Number of Deaths: 5689
Status: confirmed
=============================================
Case ID: 17145
Date: 2014-12-03 00:00:00
Number of Deaths: 6070
Status: confirmed
=============================================
Case ID: 17942
Date: 2014-12-10 00:00:00
Number of Deaths: 6388
Status: confirmed
=============================================
Case ID: 18603
Date: 2014-12-17 00:00:00
Number of Deaths: 6915
Status: confirmed
=============================================
Case ID: 19497
Date: 2014-12-24 00:00:00
Number of Deaths: 7588
Status: confirmed
=============================================
Case ID: 20206
Date: 2014-12-31 00:00:00
Number of Deaths: 7905
Status: confirmed
=============================================
Case ID: 20747
Date: 2015-01-07 00:00:00
Number of Deaths: 8235
Status: confirmed
=============================================
Case ID: 21296
Date: 2015-01-14 00:00:00
Number of Deaths: 8429
Status: confirmed
=============================================
Case ID: 21724
Date: 2015-01-21 00:00:00
Number of Deaths: 8641
Status: confirmed
=============================================
Case ID: 22092
Date: 2015-01-28 00:00:00
Number of Deaths: 8810
Status: confirmed
=============================================
Case ID: 22495
Date: 2015-02-04 00:00:00
Number of Deaths: 8981
Status: confirmed
=============================================
Case ID: 22894
Date: 2015-02-11 00:00:00
Number of Deaths: 9177
Status: confirmed
=============================================
Case ID: 23253
Date: 2015-02-18 00:00:00
Number of Deaths: 9380
Status: confirmed
=============================================
Case ID: 23729
Date: 2015-02-25 00:00:00
Number of Deaths: 9604
Status: confirmed
=============================================
Case ID: 23969
Date: 2015-03-04 00:00:00
Number of Deaths: 9807
Status: confirmed
=============================================
Case ID: 24282
Date: 2015-03-11 00:00:00
Number of Deaths: 9976
Status: confirmed
=============================================
Case ID: 24701
Date: 2015-03-18 00:00:00
Number of Deaths: 10194
Status: confirmed
=============================================
Case ID: 24907
Date: 2015-03-25 00:00:00
Number of Deaths: 10326
Status: confirmed
=============================================